spring:
  application:
    name: travel-api
  datasource:
    url: jdbc:h2:mem:travel-api
    driver-class-name: org.h2.Driver
    username: sa
    password:
  output:
    ansi:
      enabled: always
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      format_sql: true
  sql:
    init:
      mode: always
      platform: h2

travel:
  controller:
    path: /travel
    get-locations: /locations
  user: someuser
  password: psw

actuator:
  metrics:
    controller:
      path: /actuator/metrics
    username: ops
    password: psw

management:
  metrics:
    enable:
      http.server.requests: true
    export:
      prometheus:
        enabled: true
  metrics.web.server.request.autotime.enabled: true

server:
  port: 8080
logging:
  level:
    root: info
    com.afkl.travel.exercise: debug

